version: '3'
services:
  master:
      build: ./backend/master
      container_name: master
      command: ["sh", "-c", "python3 main.py"]
      environment:
        - ROLE=master
        - FLASK_DEBUG=1
      volumes:
        - ./backend:/backend/master
      ports:
        - 8080:8080

  secondary1:
      build: ./backend/secondary
      container_name: secondary1
      command: ["sh", "-c", "python3 main.py"]
      environment:
        - ROLE=secondary
        - MASTER_HOST=http://master:8080
        - FLASK_DEBUG=1
      volumes:
        - ./backend:/backend/secondary
      depends_on:
        - master
      ports:
        - 8001:8000

  secondary2:
      build:  ./backend/secondary
      container_name: secondary2
      command: ["sh", "-c", "python3 main.py"]
      environment:
        - ROLE=secondary
        - MASTER_HOST=http://master:8080
        - FLASK_DEBUG=1
      volumes:
        - ./backend:/backend/secondary
      depends_on:
        - master
      ports:
        - 8002:8000